### ISSUE TITLE
Add CS courses in the widgets component.

### ISSUE THREAD

**Issue by suryasiriki4** [suryasiriki4/untwin#4]
https://github.com/suryasiriki4/untwin/blob/master/src/components/Widgets.js

Basically, this website is for our college right. So we should add our courses on the right side of the QandA component.

Try to make it look beautiful.

**Comment by Devjoyti-Barman** [comment]
i am interested

**Comment by Devjoyti-Barman** [comment]
I have added the course component can you check that

**Comment by suryasiriki4** [comment]
Hey! please send a pull request. I would be glad to accept it.

**Comment by suryasiriki4** [comment]
Hey, really nice work. 👍 would you like to continue on any other issue...

**Comment by Devjoyti-Barman** [comment]
yes, i would be happy to contribute.
