### ISSUE TITLE
Keeping backend in server folder of "untwin"

### ISSUE THREAD

**Issue by suryasiriki4** [suryasiriki4/untwin#5]
@darahask, please add your backend to the server folder in the main repository.

this video is helpful, I guess
https://www.youtube.com/watch?v=mXqcVjdq7JM&list=PL9a7QRYt5fqnxmxDMglzfv9v47IygFkDe&index=2&ab_channel=JohnAhn

**Comment by darahask** [comment]
is it really required?
We have to keep whole front end in different folder then...

**Comment by suryasiriki4** [comment]
We can keep both of them separately and deploy. not an issue.
